image:
  repository: acrpaypal1784129343.azurecr.io/frontend-service
  tag: f37a2f16ae079b28a9e1585d94795cac2e36f75a
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 3001

imagePullSecrets:
  - name: acr-secret

ingress:
  enabled: true

  className: nginx

  # host: paypal.local

  path: /

  pathType: Prefix

config:
  appName: "Paypal Frontend"
  environment: "DEV"