image:
  repository: acrpaypal1784092813.azurecr.io/frontend-service
  tag: ""
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 3001

imagePullSecrets:
  - name: acr-secret

ingress:
  enabled: true

  className: nginx

  # host: paypal.local

  path: /

  pathType: Prefix

config:
  appName: "Paypal Frontend"
  environment: "DEV"