image:
  repository: acrpaypal1784605420.azurecr.io/frontend-service
  tag: c2f83bca964690cfb1fb9bc04cfe9566ef4d2af3
  pullPolicy: Always

replicaCount: 3

service:
  type: ClusterIP
  port: 80
  targetPort: 3001

imagePullSecrets:
  - name: acr-secret

ingress:
  enabled: true

  className: nginx

  # host: paypal.local

  path: /

  pathType: Prefix

config:
  appName: "Frontend Service"
  environment: "DEV"

secret:
  apiKey: "paypal-api-key-123"
  dbPassword: "paypal-db-password"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

  limits:
    cpu: "300m"
    memory: "256Mi"