image:
  repository: acrpaypal1784528210.azurecr.io/frontend-service
  tag: d87e23776ae6896c1dd87831a1654a032bf14e0c
  pullPolicy: Always

replicaCount: 3

service:
  type: ClusterIP
  port: 80
  targetPort: 3001

imagePullSecrets:
  - name: acr-secret

ingress:
  enabled: true

  className: nginx

  # host: paypal.local

  path: /

  pathType: Prefix

config:
  appName: "Paypal Frontend"
  environment: "DEV"

secret:
  apiKey: "paypal-api-key-123"
  dbPassword: "paypal-db-password"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

  limits:
    cpu: "300m"
    memory: "256Mi"