apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: default

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:

    metadata:
      labels:
        app: frontend

    spec:

      imagePullSecrets:
      - name: acr-secret

      containers:

      - name: frontend

        image: acrpaypal1784003128.azurecr.io/frontend-service:b56ac725d409bb8951e3d6803f853f81dc6acc10

        ports:
        - containerPort: 3001
