apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-service

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: frontend-service

  template:
    metadata:
      labels:
        app: frontend-service

    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
        
      affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app
                        operator: In
                        values:
                          - frontend-service
                  topologyKey: kubernetes.io/hostname      

      containers:
      - name: frontend-service

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        envFrom:
          - configMapRef:
              name: frontend-config

          - secretRef:
              name: frontend-secret
        
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 20
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /ready
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5

        startupProbe:
          httpGet:
            path: /health
            port: 3001
          failureThreshold: 30
          periodSeconds: 10

        resources:
          {{- toYaml .Values.resources | nindent 12 }}

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.service.targetPort }}
