apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb

data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS customers
    (
        id SERIAL PRIMARY KEY,
        name VARCHAR(100),
        email VARCHAR(100) UNIQUE,
        password VARCHAR(100),
        wallet NUMERIC(10,2)
    );

    INSERT INTO customers
    (name,email,password,wallet)
    VALUES
    ('Ganesha','ganesha@test.com','123456',5000.00),
    ('Muruga','muruga@test.com','123456',7000.00)
    ON CONFLICT (email) DO NOTHING;