image:
  repository: acrpaypal1784738856.azurecr.io/user-service
  tag: latest
  pullPolicy: Always

replicaCount: 3

service:
  type: ClusterIP
  port: 80
  targetPort: 3002

imagePullSecrets:
  - name: acr-secret

ingress:
  enabled: true

  className: nginx

  # host: paypal.local

  path: /users

  pathType: Prefix

config:
  appName: "User Service"
  environment: "DEV"

secret:
  existingSecret: user-service-secret

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

  limits:
    cpu: "300m"
    memory: "256Mi"