name: CI Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Run Semgrep Scan
      uses: semgrep/semgrep-action@v1
      with:
        config: auto

#    - name: Install Semgrep
#      run: |
#        python -m pip install semgrep

#    - name: Run Semgrep Scan
#      run: |
#        semgrep scan \
#          --config auto \
#          --error \
#          .

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Dependencies
      working-directory: devops/paypal-frontend-app/frontend-service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install wget gnupg lsb-release -y

        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
          gpg --dearmor | \
          sudo tee /usr/share/keyrings/trivy.gpg >/dev/null

        echo \
          "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | \
          sudo tee /etc/apt/sources.list.d/trivy.list

        sudo apt-get update
        sudo apt-get install trivy -y

        trivy --version

    - name: Trivy Filesystem Scan
      run: |
        trivy fs \
          --severity HIGH,CRITICAL \
          ./devops/paypal-frontend-app

    - name: Print Repository Structure
      run: |
        pwd
        find . -type d | sort

    - name: Build Docker Image
      run: |
        docker build \
          -t frontend-service:${{ github.sha }} \
          ./devops/paypal-frontend-app/frontend-service

    - name: Trivy Image Scan
      run: |
        trivy image \
          --severity HIGH,CRITICAL \
          frontend-service:${{ github.sha }}

    - name: Success
      if: success()
      run: echo "Pipeline Successful"
