name: CI Testing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Dependencies
      working-directory: devops/paypal-frontend-app/frontend-service
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Trivy
      run: |
        sudo apt-get update
        wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.65.0_Linux-64bit.deb
        sudo dpkg -i trivy_0.65.0_Linux-64bit.deb

    - name: Trivy Filesystem Scan
      run: |
        trivy fs \
          --severity HIGH,CRITICAL \
          ./devops/paypal-frontend-app

    - name: Build Docker Image
      run: |
        docker build \
          -t frontend-service:${{ github.sha }} \
          ./frontend-service

    - name: Trivy Image Scan
      run: |
        trivy image \
          --severity HIGH,CRITICAL \
          frontend-service:${{ github.sha }}
            
    - name: Debug
      run: |
        pwd
        find . -type d | sort

    - name: Success
      if: success()
      run: echo "Pipeline Successful"
