name: CD Pipeline

on:
  workflow_dispatch:

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup kubeconfig
      run: |

        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

    - name: Verify Cluster
      run: |

        kubectl cluster-info
        kubectl get nodes
        kubectl get pods -A

    - name: Deploy
      run: |

        kubectl set image deployment/frontend \
          frontend-service=${{ secrets.ACR_NAME }}.azurecr.io/frontend-service:${{ github.sha }}

        kubectl rollout status deployment/frontend